@startuml hook

actor "Git" as GitSystem
rectangle ":HookciCli" as CLI
rectangle ":CiExecutionService" as App
rectangle ":YamlConfigurationHandler" as CfgHandler
rectangle ":Configuration" as Config
rectangle ":DockerService" as DockerSvc
boundary "config" as ConfigFile
boundary "Docker" as DockerSystem

GitSystem -down-> CLI: 1: run hook
CLI -down-> App: 2: run()
App -right-> CfgHandler: 3: load_conf()
CfgHandler -right-> ConfigFile: 3.1: read config
App -left-> Config: 4: validate()
App -left-> Config: 5: get_image_info()
App -down-> DockerSvc: 6: build_dockerfile()
DockerSvc -down-> DockerSystem: 6.1: build image
App -left-> Config: 7: get_test_steps()
App -down-> DockerSvc: 8.*: run_container()
DockerSvc -down-> DockerSystem: 8.*.1: run container
@enduml
