@startuml init
!theme _none_
hide footbox

actor ":Administrador" as Admin
rectangle ":HookciCli" as CLI
rectangle ":ProjectInitializationService" as App
rectangle ":GitService" as GitSvc
rectangle ":YamlConfigurationHandler" as CfgHandler
boundary "Git" as GitSystem
boundary "config" as ConfigFile

Admin -down-> CLI: 1: hookci init
CLI -down-> App: 2: run()
App -right-> GitSvc: 3: find_git_root()
GitSvc -right-> GitSystem: 3.1: locate .git
App -down-> CfgHandler: 4: write_def_conf()
CfgHandler -down-> ConfigFile: 4.1: write default config
App -right-> GitSvc: 5: install_hooks()
GitSvc -right-> GitSystem: 5.1: create/write hook files
@enduml
