@startuml hook
skinparam defaultFontName SansSerif

boundary "Git" as GitSystem
participant "<<Presentation>>\n:HookciCli" as CLI
participant "<<Presentation>>\n:PipelineUI" as UI
participant "<<Application>>\n:CiExecutionService" as App
participant "<<Infrastructure>>\n:YamlConfigHandler" as CfgHandler
participant "<<Infrastructure>>\n:GitService" as GitSvc
participant "<<Infrastructure>>\n:DockerService" as DockerSvc
boundary "FileSystem" as FS
boundary "Docker" as Docker

GitSystem -> CLI : hookci run --hook-type pre-commit
activate CLI
CLI -> App : run(hook_type='pre-commit', ...)
activate App

App -> GitSvc : git_root
activate GitSvc
deactivate GitSvc

App -> CfgHandler : load_config_data()
activate CfgHandler
CfgHandler -> FS : read config.yaml
deactivate CfgHandler
App -> App : validate config

group Filter Checks
    App -> GitSvc : get_current_branch()
    activate GitSvc
    deactivate GitSvc
    alt filters do not match
        App --> CLI : (generator finishes)
        deactivate App
        CLI --> GitSystem : exit code 0
        deactivate CLI
        return
    end
end

CLI -> UI : new()
activate UI
CLI -> CLI : loop events from App.run()

App --> CLI : yield PipelineStart
CLI -> UI : handle_event(PipelineStart)

group Prepare Docker Image
    opt Dockerfile
        App --> CLI : yield ImageBuildStart
        CLI -> UI : handle_event(ImageBuildStart)
        App -> DockerSvc : build_image()
        activate DockerSvc
        loop build logs
            DockerSvc --> App : yield log_line
            App --> CLI : yield LogLine
            CLI -> UI : handle_event(LogLine)
        end
        deactivate DockerSvc
        App --> CLI : yield ImageBuildEnd
        CLI -> UI : handle_event(ImageBuildEnd)
    else Image Name
        App --> CLI : yield ImagePullStart
        CLI -> UI : handle_event(ImagePullStart)
        App -> DockerSvc : pull_image()
        activate DockerSvc
        deactivate DockerSvc
        App --> CLI : yield ImagePullEnd
        CLI -> UI : handle_event(ImagePullEnd)
    end
end

loop Para cada Step
    App --> CLI : yield StepStart
    CLI -> UI : handle_event(StepStart)
    App -> DockerSvc : run_command_in_container()
    activate DockerSvc
    DockerSvc --> App : return exit_code
    deactivate DockerSvc
    App --> CLI : yield StepEnd
    CLI -> UI : handle_event(StepEnd)

    alt Step Crítico Falhou
        App --> CLI : yield PipelineEnd(status="FAILURE")
        CLI -> UI : handle_event(PipelineEnd)
        deactivate App
        CLI --> GitSystem : exit code 1
        deactivate UI
        deactivate CLI
        return
    end
end

App --> CLI : yield PipelineEnd(status="SUCCESS")
deactivate App
CLI -> UI : handle_event(PipelineEnd)
deactivate UI
CLI --> GitSystem : exit code 0
deactivate CLI
@enduml
