@startuml hook
skinparam defaultFontName SansSerif

boundary "Git" as Git
participant "<<Presentation>>\n:HookciCli" as CLI
participant "<<Presentation>>\n:PipelineUI" as UI
participant "<<Application>>\n:CiExecutionService" as App
participant "<<Infrastructure>>\n:YamlConfigHandler" as CfgHandler
participant "<<Infrastructure>>\n:GitService" as GitSvc
participant "<<Infrastructure>>\n:DockerService" as DockerSvc
boundary "FileSystem" as FS
boundary "Git" as Git
boundary "Docker" as Docker

Git -> CLI : hookci run --hook-type pre-commit
activate CLI
CLI -> App : run(hook_type='pre-commit', ...)
activate App

App -> GitSvc : git_root
activate GitSvc
GitSvc -> Git : find .git
activate Git
deactivate Git
GitSvc --> App : git_root_path
deactivate GitSvc

App -> CfgHandler : load_config_data()
activate CfgHandler
CfgHandler -> FS : read config.yaml
activate FS
deactivate FS
CfgHandler --> App : config_data
deactivate CfgHandler
App -> App : validate config

group Filter Checks
    App -> GitSvc : get_current_branch()
    activate GitSvc
    GitSvc --> App : branch_name
    deactivate GitSvc
    alt filters do not match
        App --> CLI : (generator finishes)
        CLI --> Git : exit code 0
        activate Git
        deactivate Git
    end
end

CLI -> UI : new()
activate UI
CLI -> CLI : loop events from App.run()

App --> CLI : yield PipelineStart
CLI -> UI : handle_event(PipelineStart)

loop Para cada Step
    App --> CLI : yield StepStart
    CLI -> UI : handle_event(StepStart)
    App -> DockerSvc : run_command_in_container()
    activate DockerSvc
    DockerSvc -> Docker : run container
    activate Docker
    deactivate Docker
    DockerSvc --> App : return exit_code
    deactivate DockerSvc
    App --> CLI : yield StepEnd
    CLI -> UI : handle_event(StepEnd)

    alt Step Crítico Falhou
        App --> CLI : yield PipelineEnd(status="FAILURE")
        CLI -> UI : handle_event(PipelineEnd)
        CLI --> Git : exit code 1
        activate Git
        deactivate Git
    end
end

App --> CLI : yield PipelineEnd(status="SUCCESS")
deactivate App
CLI -> UI : handle_event(PipelineEnd)
deactivate UI
CLI --> Git : exit code 0
activate Git
deactivate Git
deactivate CLI

@enduml
