@startuml init
skinparam sequenceMessageAlign center

actor "Administrador" as User
participant "<<Presentation>>\n:HookciCli" as CLI
participant "<<Application>>\n:ProjectInitService" as App
participant "<<Infrastructure>>\n:YamlConfigHandler" as CfgHandler
participant "<<Infrastructure>>\n:GitService" as GitSvc
participant "<<Infrastructure>>\n:LocalFileSystem" as FS
boundary "Git" as Git
boundary "FileSystem" as FsBoundary

User -> CLI : hookci init
activate CLI
CLI -> App : run()
activate App

App -> GitSvc : git_root
activate GitSvc
GitSvc -> Git : find .git
activate Git
deactivate Git
GitSvc --> App : git_root_path
deactivate GitSvc

App -> FS : file_exists(config_path)
activate FS
FS --> App : false
deactivate FS

alt Projeto ainda não inicializado
    App -> FS : create_dir(hooks_dir)
    activate FS
    deactivate FS
    App -> CfgHandler : write_config_data()
    activate CfgHandler
    CfgHandler -> FsBoundary : write default hookci.yaml
    activate FsBoundary
    deactivate FsBoundary
    deactivate CfgHandler
    App -> FS : write_file(pre-commit script)
    activate FS
    deactivate FS
    App -> FS : write_file(pre-push script)
    activate FS
    deactivate FS
    App -> GitSvc : set_hooks_path()
    activate GitSvc
    GitSvc -> Git : git config core.hooksPath ...
    activate Git
    deactivate Git
    deactivate GitSvc
end

App --> CLI : config_path
deactivate App
CLI --> User : Exibe sucesso
deactivate CLI
@enduml
