@startuml migrate
skinparam sequenceMessageAlign center

actor "Administrador" as User
participant "<<Presentation>>\n:HookciCli" as CLI
participant "<<Application>>\n:MigrationService" as App
participant "<<Infrastructure>>\n:YamlConfigHandler" as CfgHandler
participant "<<Infrastructure>>\n:GitService" as GitSvc
boundary "FileSystem" as FS

User -> CLI : hookci migrate
activate CLI
CLI -> App : run()
activate App

App -> GitSvc : git_root
activate GitSvc
GitSvc -> FS : find .git
GitSvc --> App : git_root_path
deactivate GitSvc

App -> CfgHandler : load_config_data()
activate CfgHandler
CfgHandler -> FS : read config.yaml
CfgHandler --> App : old_config_data
deactivate CfgHandler

App -> App : process_migration()

App -> CfgHandler : write_config_data()
activate CfgHandler
CfgHandler -> FS : write updated config.yaml
deactivate CfgHandler

App --> CLI : success_message
deactivate App

CLI --> User : Exibe resultado da migração
deactivate CLI
@enduml
