@startuml run
skinparam sequenceMessageAlign center

actor "Desenvolvedor" as User
participant "<<Presentation>>\n:HookciCli" as CLI
participant "<<Presentation>>\n:PipelineUI" as UI
participant "<<Application>>\n:CiExecutionService" as App
participant "<<Infrastructure>>\n:YamlConfigHandler" as CfgHandler
participant "<<Infrastructure>>\n:GitService" as GitSvc
participant "<<Infrastructure>>\n:DockerService" as DockerSvc
boundary "FileSystem" as FS
boundary "Git" as Git
boundary "Docker" as Docker

User -> CLI : hookci run
activate CLI
CLI -> App : run(hook_type=None, ...)
activate App

App -> GitSvc : git_root
activate GitSvc
GitSvc -> Git : find .git
activate Git
deactivate Git
GitSvc --> App : git_root_path
deactivate GitSvc

App -> CfgHandler : load_config_data()
activate CfgHandler
CfgHandler -> FS : read config.yaml
activate FS
deactivate FS
CfgHandler --> App : config_data
deactivate CfgHandler
App -> App : validate config

CLI -> UI : new()
activate UI
CLI -> CLI : loop events from App.run()

App --> CLI : yield PipelineStart
CLI -> UI : handle_event(PipelineStart)

opt Dockerfile
    App --> CLI : yield ImageBuildStart
    CLI -> UI : handle_event(ImageBuildStart)
    App -> DockerSvc : build_image()
    activate DockerSvc
    DockerSvc -> Docker : build image
    activate Docker
    deactivate Docker
    loop build logs
        DockerSvc --> App : yield log_line
        App --> CLI : yield LogLine
        CLI -> UI : handle_event(LogLine)
    end
    deactivate DockerSvc
    App --> CLI : yield ImageBuildEnd
    CLI -> UI : handle_event(ImageBuildEnd)
end

loop Para cada Step
    App --> CLI : yield StepStart
    CLI -> UI : handle_event(StepStart)
    App -> DockerSvc : run_command_in_container()
    activate DockerSvc
    DockerSvc -> Docker : run container
    activate Docker
    deactivate Docker
    loop container logs
        DockerSvc --> App : yield log_line
        App --> CLI : yield LogLine
        CLI -> UI : handle_event(LogLine)
    end
    DockerSvc --> App : return exit_code
    deactivate DockerSvc
    App --> CLI : yield StepEnd
    CLI -> UI : handle_event(StepEnd)
end

App --> CLI : yield PipelineEnd
deactivate App
CLI -> UI : handle_event(PipelineEnd)
deactivate UI

CLI --> User : Exibe resultado final
deactivate CLI

@enduml
