version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    assignees:
      - 'h3nc4'
    reviewers:
      - 'h3nc4'

  - package-ecosystem: 'cargo'
    directory: '/src/wasudoku-wasm'
    schedule:
      interval: 'weekly'
    assignees:
      - 'h3nc4'
    reviewers:
      - 'h3nc4'
