@startuml help
skinparam sequenceMessageAlign center

actor "Usuário" as User
participant "Sistema" as Sys

User -> Sys : hookci help
activate Sys
Sys --> User : Exibe texto de ajuda
deactivate Sys
@enduml
