@startuml init
!theme _none_
skinparam sequenceMessageAlign center
hide footbox

actor "Administrador" as User
participant "Sistema" as Sys

User -> Sys : hookci init
activate Sys
Sys --> User : Exibe sucesso ou aviso de já inicializado
deactivate Sys
@enduml
