@startuml migrate
skinparam sequenceMessageAlign center

actor "Administrador" as User
participant "Sistema" as Sys

User -> Sys : hookci migrate
activate Sys
Sys --> User : Exibe resultado da migração
deactivate Sys
@enduml
