@startuml classes
skinparam packageStyle rectangle

package "Presentation" <<Rectangle>> {
    class HookciCli <<CLI>> {
        + init()
        + run(str, bool)
        + migrate()
        + main()
    }

    class PipelineUI <<UI>> {
        + handle_event(PipelineEvent, Live)
    }

    class DebugUI <<UI>> {
        + handle_event(PipelineEvent)
    }
}

package "Application" <<Rectangle>> {
    class ProjectInitService <<Service>> {
        + run()
    }

    class CiExecutionService <<Service>> {
        + run(str, bool)
    }

    class MigrationService <<Service>> {
        + run()
    }

    package "events" {
        interface PipelineEvent <<DTO>>
    }
}

package "Domain" <<Rectangle>> {
    class Configuration <<Model>> {
        + version: str
        + log_level: LogLevel
        + docker: Docker
        + hooks: Hooks
        + filters: Filters
        + steps: List<Step>
        + validate_dag()
    }
}

package "Infrastructure" <<Rectangle>> {
    interface IFileSystem <<Interface>> {
        + file_exists(Path)
        + create_dir(Path)
        + write_file(Path, str)
        + read_file(Path)
        + make_executable(Path)
    }
    class LocalFileSystem <<Implementation>> {
        + file_exists(Path)
        + create_dir(Path)
        + write_file(Path, str)
        + read_file(Path)
        + make_executable(Path)
    }

    interface IScmService <<Interface>> {
        + git_root
        + set_hooks_path(hooks_Path)
        + get_current_branch()
        + get_staged_commit_message()
    }
    class GitService <<Implementation>> {
        + git_root
        + set_hooks_path(hooks_Path)
        + get_current_branch()
        + get_staged_commit_message()
    }

    interface IDockerService <<Interface>> {
        + image_exists(str)
        + pull_image(str)
        + run_cmd(str, str, Path, Dict)
        + build_image(Path, str)
        + count_dockerfile_steps(Path)
        + calculate_dockerfile_hash(Path)
        + start_container(str, Path)
        + exec(str, str, Dict)
        + remove_container(str)
    }
    class DockerService <<Implementation>> {
        + image_exists(str)
        + pull_image(str)
        + run_cmd(str, str, Path, Dict)
        + build_image(Path, str)
        + count_dockerfile_steps(Path)
        + calculate_dockerfile_hash(Path)
        + start_container(str, Path)
        + exec(str, str, Dict)
        + remove_container(str)
    }

    interface IConfigHandler <<Interface>> {
        + load_config_data(Path)
        + write_config_data(Path, Dict)
    }
    class YamlConfigHandler <<Implementation>> {
        + load_config_data(Path)
        + write_config_data(Path, Dict)
    }

    LocalFileSystem .up.|> IFileSystem
    GitService .up.|> IScmService
    DockerService .up.|> IDockerService
    YamlConfigHandler .up.|> IConfigHandler
}

HookciCli -down-> ProjectInitService
HookciCli -down-> CiExecutionService
HookciCli -down-> MigrationService
PipelineUI --> PipelineEvent
DebugUI --> PipelineEvent

ProjectInitService --> Configuration
CiExecutionService --> Configuration
MigrationService --> Configuration

ProjectInitService --> IScmService
ProjectInitService --> IFileSystem
ProjectInitService --> IConfigHandler

CiExecutionService --> IScmService
CiExecutionService --> IConfigHandler
CiExecutionService --> IDockerService
CiExecutionService --> IFileSystem

MigrationService --> IScmService
MigrationService --> IConfigHandler

GitService --> IFileSystem
YamlConfigHandler --> IFileSystem

@enduml