@startuml estados

state "Aguardando" as Aguardando : Gatilho pendente
state "Inicializando" as Init : Carrega Cfg / Prepara Docker
state "Executando" as Exec : Executa Etapas Teste
state "Depurando" as Debug : Sessão Depuração
state "FimExecucao" as Fim <<choice>>

state "Sucesso" as Success <<end>>
state "Falha" as Failed <<end>>

[*] --> Aguardando

Aguardando --> Init : Gatilho Disparado

Init --> Exec : Inicialização OK
Init --> Failed : Falha ao Inicializar

Exec --> Fim : Etapas OK

Exec --> Debug : Etapa Falhou\n[debug ativo]
Debug --> Failed : Fim Depuração

Exec --> Failed : Etapa Crítica Falhou

Fim --> Success : Sucesso

@enduml
