@startuml pacotes

package "hookci" {
    package "presentation" as PresentationLayer {
        package "cli" as CLI {
        }
    }
    package "application" as ApplicationLayer {
        package "services" as Services {
        }
        package "events" as Events {
        }
    }
    package "domain" as DomainLayer {
        package "config" as DomainConfig {
        }
    }
    package "infrastructure" as InfrastructureLayer {
        package "fs" as InfraFs {
        }
        package "docker" as InfraDocker {
        }
        package "yaml_handler" as InfraYAML {
        }
    }
}
PresentationLayer ..> ApplicationLayer
ApplicationLayer .left.> DomainLayer
ApplicationLayer ..> InfrastructureLayer
@enduml
