name: Release Server Build
description: 'Build JAR bundle for release and Docker image'

on:
  push:
    tags: [ 'v*.*.*' ]

jobs:
  release-server:
    runs-on: ubuntu-latest
    container:
      image: maven:3.9-eclipse-temurin-21
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Build JAR
        run: |
          cd source/backend/api-central/ && \
          mvn clean package -Dmaven.test.skip=true && \
          mv target/*.jar ../api-central-${{ github.ref_name }}.jar
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            source/backend/api-central-${{ github.ref_name }}.jar
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}

  release-server-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./source/backend/
          push: true
          tags: ghcr.io/${{ secrets.DOCKER_USERNAME }}/pmmg:latest
