name: Release Server Build
description: 'Build JAR bundle for release and Docker image'

on:
  push:
    tags: [ 'v*.*.*' ]

jobs:
  release:
    runs-on: ubuntu-latest
    container:
      image: debian:trixie
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Install dependencies
        run: |
          apt-get update && \
          DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
            curl \
            maven \
            openjdk-21-jdk-headless
      - name: Build JAR
        run: |
          cd source/backend/api-central/ && \
          mvn clean package -Dmaven.test.skip=true && \
          mv target/*.jar ../api-central-${{ github.ref_name }}.jar
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            source/backend/api-central-${{ github.ref_name }}.jar
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: api-central-${{ github.ref_name }}
          path: source/backend/api-central-${{ github.ref_name }}.jar
          retention-days: 1

  release-docker:
    runs-on: ubuntu-latest
    needs: release
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Download JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: api-central-${{ github.ref_name }}
          path: ./source/backend/
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./source/backend/
          push: true
          tags: ghcr.io/${{ secrets.DOCKER_USERNAME }}/pmmg:latest
